name: Reclaim The Stack - Rubocop
description: Runs rubocop and posts offences as inline PR comments.
inputs:
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  gem_versions:
    description: Gem versions to install
    default: rubocop:1.64.1 rubocop-rails:2.25.0 rubocop-rspec:2.30.0
  rubocop_arguments:
    description: Arguments passed to rubocop cli
    default: ""
  outside_diff_fail:
    description: Fail build for offences found outside of PR diff
    default: "true"
runs:
  using: composite
  steps:
    - run: ruby $GITHUB_ACTION_PATH/rubocop.rb ${{ inputs.rubocop_arguments }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUBOCOP_GEM_VERSIONS: ${{ inputs.gem_versions }}
        OUTSIDE_DIFF_FAIL: ${{ inputs.outside_diff_fail }}
